### ISSUE TITLE
Playground uses old version?

### ISSUE THREAD

**Issue by saschasc** [evan-liu/karabiner.ts#110]
I had played around a bit in the Playground and wondered why one feature wasn't working. Could it be that the Playground is not using the latest version? When I run the ts script locally it works as expected.

**Comment by saschasc** [comment]
I am using the feature introduced with 1.25. In the output I miss the `bundle_identifiers`.
```
import {
  rule,
  map,
  ifApp,
} from 'karabiner.ts'

var appFilter = ifApp(
  {
    bundle_identifiers: [
      '^com\\.jetbrains'
    ],
    file_paths: [
      '^/usr/local/bin/qemu-system-x86_64$'
    ]
  }).unless().build();

  export const rules = () => [

  rule('Option key mappings', appFilter).manipulators([

      map('2', '⌥').to('g', '⌥')  // # Option + 2 -> @
  ]),
]
```

**Comment by evan-liu** [comment]
Yes, you are right, I checked in the `package-lock.json` which causes the playground only to install an old version. I've [deleted the file](https://github.com/evan-liu/karabiner.ts.playground/commit/a837740693ede29dbe4672ea526d1211e3bf401b) so it should work now, could you please give it another try? Thanks!

**Comment by saschasc** [comment]
Works like a charm!

Thanks for this great project. Would be great if this could be a core part of Karabiner itself.
