### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by frankfriberg** [evan-liu/karabiner.ts#121]
I can't access the docs, just gives me a 404

**Comment by evan-liu** [comment]
Thanks, can you try https://evan-liu.github.io/karabiner.ts/ in an incognito window? I've just removed CNAME and it might be a browser cache of the old CNAME record.

**Comment by seanwash** [comment]
I'm having the same issue – tried in an incognito window and I still get a 404, however trying on my phone (which hadn't previously ever visited the docs site) and I'm able to access the docs.

**Comment by evan-liu** [comment]
GitHub says it is [the browser cache](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#browser-cache). One workaround works for me is to visit a subpage instead of `/`. Like https://evan-liu.github.io/karabiner.ts/utils. Could you try if it works for you too? Sorry about that.

**Comment by seanwash** [comment]
> GitHub says it is [the browser cache](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#browser-cache). One workaround works for me is to visit a subpage instead of `/`. Like https://evan-liu.github.io/karabiner.ts/utils. Could you try if it works for you too? Sorry about that.

That seems to have worked for me 👍

**Comment by frankfriberg** [comment]
> GitHub says it is [the browser cache](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#browser-cache). One workaround works for me is to visit a subpage instead of `/`. Like https://evan-liu.github.io/karabiner.ts/utils. Could you try if it works for you too? Sorry about that.

Works for me 🎉
