### ISSUE TITLE
Notification for simlayer?

### ISSUE THREAD

**Issue by sherwinyu** [evan-liu/karabiner.ts#152]
It appears `notification` is not supported for simlayer -- I get the following error:
```
Property 'notification' does not exist on type 'SimlayerRuleBuilder'. ts (2339) [38, 36]
```

Here's the full code snippet, in case it's relevant:
```
  simlayer('d', 'navigation mode').notification('nav mode').manipulators([
    map('h').to('left_arrow'),
    map('l').to('right_arrow'),
    map('k').to('up_arrow'),
    map('j').to('down_arrow'),

    map('a').to('left_arrow', 'command'),
    map(';').to('right_arrow', 'command'),

    map('f').to('left_option'),
    map('s').to('left_shift'),
  ]),

```

I'm assuming it's just because notification isn't supported for simlayer (and not that I'm doing something wrong -- please correct me if I am though).

Would it be possible to add this? I took a look at https://github.com/evan-liu/karabiner.ts/pull/96 -- not sure how hard this would be.

P.S., thanks for this great library -- this has made managing and iterating on Karabiner configurations way, way more reasonable (the type safety autocomplete is super helpful).

**Comment by evan-liu** [comment]
Thanks for using karabiner.ts and glad to hear it is useful. You are right that notification is not supported right now. For layers notifications are useful as it shows up before triggering any actions. However simlayer is only activated when one of the keys on the layer is pressed, so the notifications are only shown after one action is triggered. I was not sure how useful it would be. Would it be useful for you when it only show after one action is triggered?

**Comment by evan-liu** [comment]
BTW can you try if this works: 

```ts
simlayer('d', 'navigation mode')
  .toIfActivated(toNotificationMessage('simlayer-d', 'Navigation Mode'))
  .toIfDeactivated(toRemoveNotificationMessage('simlayer-d'))
  .manipulators([
    //...
  ]),
```

If it does and you find it useful after a while, I will add the `notification()` method like `layer()`.

**Comment by sherwinyu** [comment]
The `toIfActivated` / `toIfDeactivated` approach works. Thank you!

> However simlayer is only activated when one of the keys on the layer is pressed, so the notifications are only shown after one action is triggered. 

And I think you're right -- I'm not sure how useful this is for simlayer, but the workaround is sufficient for now. I'll report back if I find other uses for it with simlayer
