### ISSUE TITLE
Modifier Key Layers

### ISSUE THREAD

**Issue by snilan** [evan-liu/karabiner.ts#92]
First off, thank you so much for all the work you've done. I've been using a different Karabiner config generator for a bit over a year but yours has dramatically reduced the amount of code I had and made it easier to read.

In my current config, I use both the "left_option" and "right_option" keys as layer keys themselves, without any additional keys. From what I've gathered this isn't really possible although I've kinda made it work

**Comment by evan-liu** [comment]
Hi, thank you for trying out the project and I'm glad you're enjoying it so far. 

For the modifier layer, are you expecting it to disable the modifier function and serve only as a layer? Or, for example, will the `left_option` layer with keys `a` and `b` still work as a `left_option` for other keys?

**Comment by snilan** [comment]
I use `left_option` to remap my home row to the number row + a few more keys and then I use `left_option` + `spacebar` for the number row + `shift`. I think I ended up with a good solution:
```ts
const leftOptionLayer = rule(
  "Left Option -> number pad"
).manipulators([
  withMapper(homeRowKeys)((k, i) =>
    map(k, "left_option", "shift").to(
      ((i + 1) % 10).toString() as NumberKeyCode
    )
  ),
  withMapper({
    q: "grave_accent_and_tilde",
    i: "hyphen",
    o: "equal_sign",
    p: "delete_or_backspace",
    comma: "comma",
    period: "period",
  })((k, v) => map(k, "left_option", "shift").to(v as ToKeyCode)),
  map("spacebar", "left_option").to("left_option", "left_shift"),
])
```

**Comment by evan-liu** [comment]
Thanks for sharing; that's neat. I was inspired and started [trying a keypad layer](https://github.com/evan-liu/karabiner-config/commit/b731815490379095ee75619bc994efd6ead98b71) myself.

I think layers are like making regular keys work as modifiers. It may create confusion and surprises to make modifiers work as layers without adding much value to what can already be done with your mappings.

**Comment by saif97** [comment]
Hi @evan-liu, I just came across this awesome project. For every minute using GokuRakuJoudo, I wanted such a tool. 

I started migrating my configs over, however one feature I couldn't do here is using the left_command as my vim(aka fnCommand) layer mode. While active, 
- j,k,l,i -> my arrow keys.
- d, s   -> left_command, left_option
- u, o   -> home, end
- many more

I think this can be easily done if `layer` accepts `SideModifierAlias`. I don't see it's possible to do in `modifierLayer` since it requires a key to be pressed to activate that layer. 

To answer your question above, I don't want left_command to behave as "command". For that, I use "caps lock" key.

My GokuRakuJoudo looks like this; you can find the full config [here](https://github.com/saif97/dotfiles/blob/main/karabiner.edn).

```
 :layers {
          :fnCommand              {:key     :left_command}

.
.
.
.

 :main [{:des "Vi Mode [left_command as Trigger Key]"
         :rules [;
                ;  :vi_mode
                 :fnCommand

                ;; indent and un-indent
                 [:##q :!Stab]

                 [:escape :!CSw]

                 ;  arrow keys
                 [:##k :down_arrow]
                 [:##i :up_arrow]
                 [:##j :left_arrow]
                 [:##l :right_arrow]

                ;;  delete & backspace
                 [:##h :delete_forward]
                 [:##n :delete_or_backspace]

               
                 [:##d :left_option]
                 [:##s :right_shift nil {:alone :!!d}]
                ;;  home/ end
                 [:##u :!Cleft_arrow]
                 [:##o :!Cright_arrow]

                ;;  chrome stuff
                 [:##slash :!Cw]
                 [:##comma :!TStab]
                 [:##period :!Ttab]
                 [:##m :!CSf]
                ;;  desktop switching
                 [:open_bracket :!Tleft_arrow]
                 [:close_bracket :!Tright_arrow]

                ;; back & forward in browser & editors
                 [:!Sopen_bracket :!Copen_bracket]
                 [:!Sclose_bracket :!Cclose_bracket]

                 [:##c :!COsemicolon] ; trigger screenshoot.
                 [:##w :!Oleft_shift  nil {:alone :tab}]

                 [:##tab :!Ctab] ; app switcher
                 ]}


```

**Comment by evan-liu** [comment]
Hi, @saif97, thanks for trying the project. Could you please try if this works for you? 

```typescript
  rule('left-cmd').manipulators([
    withModifier('‹⌘')([
      {
        h: toKey('←'),
        j: toKey('↓'),
        k: toKey('↑'),
        l: toKey('→'),
        '⇥': toKey('⇥', '⌘'),
        // ... other one-key mappings
      },

      map('[', '⇧').to('[', '⌘'),
      map('w').to('‹⇧').toIfAlone('⇥'),
      // ... other mappings
    ]),
  ]),
```
