### ISSUE TITLE
Accidental System Diagnostics

### ISSUE THREAD

**Issue by snilan** [evan-liu/karabiner.ts#93]
A consideration is that with the Hyper Key, there can be some accidental system diagnostics that are run. They use a lot of memory and take quite a while. Perhaps they should be disabled by default?
See this article for details:

https://xam.io/2020/macos-diag-shortcuts/

**Comment by evan-liu** [comment]
Thank you for pointing it out. Could you please explain a bit more what you mean by "disabled by default"?
