### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by cvladan** [evan-liu/karabiner.ts#98]
First of all, thank you for the effort you put into making this tool!

I need help as I thought I had understood this tool but I haven't, or rather I just can't set up what I need, and here's what I need:

1. when I press "command" twice, I want to get F16
2. when I press "command" once, I want to get F15
3. I want the "command" key to still work normally as a modifier in any combination with other keys.

I tried this code:

```
mapDoubleTap('left_command', 'optionalAny').to('f16').singleTap(toKey('f15'))
```

The first and second requirements work. The third - which is the most important one - doesn't.

What am I doing wrong?

**Comment by evan-liu** [comment]
Thanks for trying out the tool. Sorry, but I am afraid what you want is not supported. Double tap is based on [to-delayed-action](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-delayed-action/), which will always trigger either `to_if_invoked` or `to_if_canceled` and make it unusable as a modifier. I use single tap on modifiers and find even that makes modifiers hard to use sometimes (and I use [duo-modifiers](https://github.com/evan-liu/karabiner-config/blob/main/src/index.ts#L28) instead).
